# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: opentelemetry-instrumentation-click
  version: "0.60b1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_click-${{ version }}.tar.gz
  sha256: 530da3e9abb05e1cb7198f210487f08020f71ef0f299ff3b2414e9a2547930bf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-semantic-conventions ==${{ version }}
    - wrapt >=1.0.0,<2.0.0
    - click >=8.1.3,<9.0.0

tests:
  - python:
      imports:
        - opentelemetry
        - opentelemetry.instrumentation.click
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Click instrumentation for OpenTelemetry
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-click
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
